package com.github.quaoz.common.database.v2;

/**
 * Used to handle records
 *
 * @param <T> The type of the record
 */
public interface RecordHandler<T extends Comparable<T>> {
	/**
	 * Returns the records length
	 */
	int recordLength();

	/**
	 * Constructs a new record from the given string generated by {@link T#toString()}
	 */
	T getRecord(String source);
}
