package com.github.quaoz.tasks.swing2;

import com.intellij.uiDesigner.core.Spacer;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

public class SubmitRecordForm {
	private JPanel panel;
	private JTextField speciesField;
	private JTextField locationField;
	private JTextField dateField;
	private JLabel speciesLabel;
	private JLabel locationLabel;
	private JLabel dateLabel;
	private JTextField sizeField;
	private JLabel sizeLabel;
	private JLabel titleLabel;
	private JButton submitButton;
	private JButton cancelButton;

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	public SubmitRecordForm() {
		submitButton.addActionListener(e -> {
			// Submit record
		});

		cancelButton.addActionListener(e -> {
			// Go back
		});
	}

	public static void main(String[] args) {
		JFrame frame = new JFrame("SubmitRecordForm");
		frame.setContentPane(new SubmitRecordForm().panel);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.pack();
		frame.setVisible(true);
	}

	public JPanel get() {
		return panel;
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel = new JPanel();
		panel.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:d:grow", "center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow"));
		panel.setMinimumSize(new Dimension(200, 220));
		panel.setPreferredSize(new Dimension(200, 220));
		speciesField = new JTextField();
		CellConstraints cc = new CellConstraints();
		panel.add(speciesField, cc.xy(5, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
		locationField = new JTextField();
		panel.add(locationField, cc.xy(5, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
		dateField = new JTextField();
		panel.add(dateField, cc.xy(5, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
		final Spacer spacer1 = new Spacer();
		panel.add(spacer1, cc.xy(5, 1, CellConstraints.DEFAULT, CellConstraints.FILL));
		final Spacer spacer2 = new Spacer();
		panel.add(spacer2, cc.xy(5, 17, CellConstraints.DEFAULT, CellConstraints.FILL));
		final Spacer spacer3 = new Spacer();
		panel.add(spacer3, cc.xy(7, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
		final Spacer spacer4 = new Spacer();
		panel.add(spacer4, cc.xy(1, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
		speciesLabel = new JLabel();
		speciesLabel.setText("Species");
		panel.add(speciesLabel, cc.xy(3, 5));
		locationLabel = new JLabel();
		locationLabel.setText("Location");
		panel.add(locationLabel, cc.xy(3, 7));
		dateLabel = new JLabel();
		dateLabel.setText("Date");
		panel.add(dateLabel, cc.xy(3, 9));
		sizeField = new JTextField();
		panel.add(sizeField, cc.xy(5, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
		sizeLabel = new JLabel();
		sizeLabel.setText("Size");
		panel.add(sizeLabel, cc.xy(3, 11));
		titleLabel = new JLabel();
		titleLabel.setText("Add Record");
		panel.add(titleLabel, cc.xy(5, 3));
		submitButton = new JButton();
		submitButton.setText("Submit");
		panel.add(submitButton, cc.xy(5, 13));
		cancelButton = new JButton();
		cancelButton.setText("Cancel");
		panel.add(cancelButton, cc.xy(5, 15));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel;
	}
}
