@startuml
'https://plantuml.com/class-diagram

+class DataBase {
- DataBaseCache cache
- long recordCount
- File location
- int length

- byte[] getRecordBytes()
- long updateRecordCount()

+ long getRecordCount()

+ void appendRecord()
+ void writeRecord()
+ void insertRecord()
+ void deleteRecord()

+ byte[] getRecord()
+ long findRecord()
}

class DataBaseCache {
- ArrayList<LongObjectImmutablePair<byte[]>> cache
- int defaultCacheSize
- int defaultCache
- int cacheIndex

+ void addRecord()
+ byte[] getRecord()

}

DataBase *- DataBaseCache

@enduml
