@startuml
'https://plantuml.com/class-diagram

+class DataBase {
- {static} int defaultCacheSize
- DataBaseCache cache
- long recordCount
- File location
- int length

- byte[] getRecordBytes()
- long updateRecordCount()

+ long getRecordCount()

+ void appendRecord()
+ void writeRecord()
+ void insertRecord()
+ void deleteRecord()

+ byte[] getRecord()
+ long findRecord()
}

class DataBaseCache {
- ArrayList<LongObjectImmutablePair<byte[]>>
}

DataBase *- DataBaseCache

@enduml
